"""delete real_name

Revision ID: 1966229d0784
Revises: ac38e1847512
Create Date: 2017-02-28 20:12:14.953851

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1966229d0784'
down_revision = 'ac38e1847512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('real_name', table_name='users')
    op.drop_column('users', 'real_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('real_name', mysql.VARCHAR(length=64), nullable=True))
    op.create_index('real_name', 'users', ['real_name'], unique=True)
    # ### end Alembic commands ###
