"""change the unique

Revision ID: 65f4cc852064
Revises: 73cf2f25e126
Create Date: 2017-02-22 20:55:31.257799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65f4cc852064'
down_revision = '73cf2f25e126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'articles', ['title'])
    op.create_unique_constraint(None, 'categorys', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categorys', type_='unique')
    op.drop_constraint(None, 'articles', type_='unique')
    # ### end Alembic commands ###
