"""add album

Revision ID: a99f57479ad5
Revises: 48dd44eacf43
Create Date: 2017-03-10 10:07:12.710738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a99f57479ad5'
down_revision = '48dd44eacf43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('photo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'photos', ['photo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'photo_id')
    # ### end Alembic commands ###
