"""change unique

Revision ID: ac38e1847512
Revises: 65f4cc852064
Create Date: 2017-02-25 23:28:35.652701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac38e1847512'
down_revision = '65f4cc852064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='categorys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'categorys', ['name'], unique=True)
    # ### end Alembic commands ###
